# Generated by Django 2.1.4 on 2019-01-10 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0002_auto_20190110_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrecord',
            old_name='name',
            new_name='first_name',
        ),
    ]
